plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  
theme: jekyll-theme-minimal
show_downloads: true
logo: /assets/logo-roosters.png
description: Descrição do tutorial. Altere isso em __config.yml .
